### ISSUE TITLE
About the process_long_input.py

### ISSUE THREAD

**Issue by MingYangi** [wzhouad/ATLOP#26]
I got the error, could you help me ? thank you!

Traceback (most recent call last):
  File "train.py", line 228, in <module>
    main()
  File "train.py", line 216, in main
    train(args, model, train_features, dev_features, test_features)
  File "train.py", line 74, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps)
  File "train.py", line 38, in finetune
    outputs = model(**inputs)
  File "D:\Anaconda\envs\pytorch-GPU\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\code\ATLOP\model.py", line 95, in forward
    sequence_output, attention = self.encode(input_ids, attention_mask)
  File "D:\code\ATLOP\model.py", line 32, in encode
    sequence_output, attention = process_long_input(self.model, input_ids, attention_mask, start_tokens, end_tokens)
  File "D:\code\ATLOP\long_seq.py", line 17, in process_long_input
    output_attentions=True,
  File "D:\Anaconda\envs\pytorch-GPU\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_attentions'

**Comment by wzhouad** [comment]
Make sure your ``transformers'' version is at least 3.4.0.

**Comment by MingYangi** [comment]
OK，thank you very much! Furthemore, α(s, o) = q(s,o)/1T q(s,o),what does this formula mean? Looking at the code, I wonder if I mean the rows of q(s,o)?

**Comment by wzhouad** [comment]
Yes. It means normalizing the q(s,o) for entity pairs such that a(s,o) is an attention distribution over the document.
